# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/
            anonymous: ~
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /
                failure_path: fos_login_failure
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                secret: %secret%


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
